### ISSUE TITLE
Windows EXE Flagged as Malware

### ISSUE THREAD

**Issue by leightonc1** [rikodot/kardi_notes_app#3]
The Windows .exe downloaded from https://www.kardi.tech/notes/downloads/kardi%20notes.exe is flagged as malware by Firefox and ESET endpoint security. See screenshots and ESET logs below for more information. 
Detection Description from ESET Endpoint Security log: a variant of MSIL/Packed.Appacker.A suspicious application
Detection Information from ESET Endpoint Security log: Event occurred on a file modified by the application: C:\Program Files\Mozilla Firefox\firefox.exe (06C8000D7CB235DA07520CED1E190B9C96356F61).

![image](https://github.com/user-attachments/assets/a12872e0-fade-4116-86b7-9ee0db8dab3a)
![image](https://github.com/user-attachments/assets/480014ca-baac-46c8-b1b3-6bf657a047df)

**Comment by rikodot** [comment]
Hello, this is happening because of the way the app is compiled and packed. Flutter produces multiple files (exe and assets) and I pack them into a singular exe using [Appacker](https://github.com/SerGreen/Appacker). This makes the file being falsely flagged as a malware. You can compile the source code yourself to be sure.
